### ISSUE TITLE
nvm to nodenv

### ISSUE THREAD

**Issue by PeterTeng** [PeterTeng/dotfiles#6]
### Check

- [Qiita](http://qiita.com/1000ch/items/41ea7caffe8c42c5211c)
- [Github - Nodenv](https://github.com/nodenv/nodenv)

### TODO

- [ ] delete nvm path in `.bash_profiles`
- [ ] `git clone git://github.com/nodenv/nodenv.git ~/.nodenv`
- [ ] Add path for nodenv
- [ ] Restart shell
- [ ] Add plugin --> `node-build`

### Path

```bash
export PATH="$HOME/.nodenv/bin:$PATH"
eval "$(nodenv init -)"
```

### Plugin

`git clone https://github.com/nodenv/node-build.git ~/.nodenv/plugins/node-build`

#### Usage

`nodenv install 5.11.1` and `nodenv rehash`

#### Can

```
$ nodenv global 6.0.0
$ nodenv local 6.5.0
```
